spring:
  datasource:
    url: jdbc:mysql://34.136.219.187:3306/pattern-prodigy-game-db?false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: PAttErN-prOdIGY-HashiRA2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'validate'
